export type TreeParams = Record<string, number | string | boolean>;

export const DEFAULT_TREE_PARAMS: TreeParams = {
  // Instance & environment
  "vegetation.instance.age01": 1.0, age01: 1.0,
  "vegetation.env.moisture": 0.55, moisture: 0.55,
  "vegetation.env.timeOfDay": 0.45, timeOfDay: 0.45,
  "vegetation.env.autoSun": true, autoSun: true,
  "vegetation.env.autoSunInfluence": 0.82, autoSunInfluence: 0.82,
  "vegetation.env.atmosphereStrength": 0.45, atmosphereStrength: 0.45,
  "vegetation.env.contactShadowStrength": 0.62, contactShadowStrength: 0.62,
  "vegetation.env.contactShadowRadius_m": 1.65, contactShadowRadius_m: 1.65,
  "vegetation.env.shadowSoftness": 0.55, shadowSoftness: 0.55,
  "vegetation.env.nearFieldAOStrength": 0.36, nearFieldAOStrength: 0.36,
  "vegetation.env.canopySelfShadow": 0.48, canopySelfShadow: 0.48,

  // Species / trunk
  "vegetation.species.profile": "BROADLEAF_DECIDUOUS", speciesProfile: "BROADLEAF_DECIDUOUS",
  height: 8, "vegetation.species.heightBase_m": 8,
  baseRadius: 0.4, "vegetation.trunk.baseRadius_m": 0.4,
  taperExponent: 0.7, "vegetation.trunk.taperExponent": 0.7,
  baseFlare: 1.3, "vegetation.trunk.baseFlare": 1.3,
  twist: 0, "vegetation.trunk.twist_deg": 0,
  "vegetation.trunk.barkColor": "#5d4037", trunkColor: "#5d4037",
  "vegetation.trunk.barkTexture": "FURROWED", barkTexture: "FURROWED",
  "vegetation.trunk.barkRoughness": 0.75, barkRoughness: 0.75,
  "vegetation.trunk.barkAnisotropy": 0.34, barkAnisotropy: 0.34,
  "vegetation.trunk.barkMicroDetail": 0.44, barkMicroDetail: 0.44,
  "vegetation.trunk.barkCurvatureDetail": 0.4, barkCurvatureDetail: 0.4,
  "vegetation.trunk.gestureKnotCount": 2, trunkKnotCount: 2,
  "vegetation.trunk.gestureKnotStrength": 0.25, trunkKnotStrength: 0.25,
  "vegetation.trunk.gestureKnotWidth": 0.12, trunkKnotWidth: 0.12,
  "vegetation.trunk.ovality": 0.06, trunkOvality: 0.06,
  "vegetation.trunk.flutingStrength": 0, trunkFlutingStrength: 0,
  "vegetation.trunk.flutingCount": 4, trunkFlutingCount: 4,
  "vegetation.trunk.flutingSharpness": 2, trunkFlutingSharpness: 2,
  "vegetation.trunk.buttressStrength": 0, buttressStrength: 0,
  "vegetation.trunk.buttressCount": 4, buttressCount: 4,
  "vegetation.trunk.buttressSharpness": 2.2, buttressSharpness: 2.2,

  // Bark
  "vegetation.bark.branchScale": 0.65, branchBarkScale: 0.65,

  // Branching
  "vegetation.branching.model": "L_SYSTEM", branchModel: "L_SYSTEM",
  "vegetation.branching.phyllotaxis": "ALTERNATE", phyllotaxis: "ALTERNATE",
  "vegetation.branching.maxOrder": 5, maxOrder: 5,
  "vegetation.branching.probability": 0.65, branchProbability: 0.65,
  "vegetation.branching.apicalDominance": 0.7, apicalDominance: 0.7,
  "vegetation.branching.angleMean_deg": 35, branchAngle: 35,
  "vegetation.branching.angleVariance_deg": 12, branchAngleVar: 12,
  "vegetation.branching.lengthDecay": 0.72, lengthDecay: 0.72,
  "vegetation.branching.radiusDecay": 0.65, radiusDecay: 0.65,
  "vegetation.branching.mainBranchCount": 6, branchCount: 6,
  "vegetation.branching.lengthRatio": 0.55, branchLength: 0.55,
  "vegetation.branching.collarStrength": 0.38, collarStrength: 0.38,
  "vegetation.branching.collarLength": 0.15, collarLength: 0.15,
  "vegetation.branching.junctionMetaballStrength": 0.55, junctionMetaballStrength: 0.55,
  "vegetation.branching.junctionMetaballRadius": 1.45, junctionMetaballRadius: 1.45,
  "vegetation.branching.unionBlendLength": 0.22, unionBlendLength: 0.22,
  "vegetation.branching.unionBlendStrength": 0.58, unionBlendStrength: 0.58,
  "vegetation.branching.unionAsymmetry": 0.42, unionAsymmetry: 0.42,
  "vegetation.branching.gestureKnotStrength": 0.25, branchKnotStrength: 0.25,
  "vegetation.branching.gestureKnotWidth": 0.18, branchKnotWidth: 0.18,
  "vegetation.branching.ovality": 0.05, branchOvality: 0.05,
  "vegetation.branching.breakProbability": 0, breakProbability: 0,
  "vegetation.branching.breakSeverity": 0.5, breakSeverity: 0.5,
  "vegetation.branching.attractorCount": 220, attractorCount: 220,
  "vegetation.branching.maxIterations": 18, maxIterations: 18,
  "vegetation.crown.crownRadiusRatio": 0.42, crownRadiusRatio: 0.42,

  // Leaves
  "vegetation.leaves.representation": "CLUSTERS", leafRepresentation: "CLUSTERS",
  "vegetation.leaves.shape": "BROADLEAF", leafShape: "BROADLEAF",
  "vegetation.leaves.colorBase": "#4a7c3f", leafColor: "#4a7c3f",
  "vegetation.leaves.colorVariation": 0.15, leafColorVariation: 0.15,
  "vegetation.leaves.size_m": 0.08, leafSize: 0.08,
  "vegetation.leaves.clusterSize": 12, leafClusterSize: 12,
  "vegetation.leaves.cardsPerMeter": 8, leafDensity: 8,
  "vegetation.leaves.petioleLengthFactor": 0.35, petioleLengthFactor: 0.35,
  "vegetation.leaves.petioleDroop": 0.35, petioleDroop: 0.35,
  "vegetation.leaves.petioleWidthFactor": 0.07, petioleWidthFactor: 0.07,

  // Wind
  "vegetation.wind.gustStrength": 0.6, windStrength: 0.6,
  "vegetation.wind.enabled": true, windEnabled: true,
  "vegetation.wind.trunkBend": 0.02, trunkBend: 0.02,
  "vegetation.wind.branchBend": 0.08, branchBend: 0.08,
  "vegetation.wind.twigBend": 0.25, twigBend: 0.25,
  "vegetation.wind.canopyShear": 0.12, canopyShear: 0.12,
  "vegetation.wind.phaseRandom": 0.8, phaseRandom: 0.8,
  "vegetation.wind.restLean": 0.22, restLean: 0.22,
  "vegetation.wind.gustFrequency": 1.0, windGustFrequency: 1.0,
  "vegetation.wind.directionVariance": 0.35, windDirectionVariance: 0.35,
  "vegetation.wind.turbulence": 0.5, windTurbulence: 0.5,
  "vegetation.wind.leafFlutter": 0.35, leafFlutter: 0.35,
  "vegetation.wind.hierarchyBias": 0.75, windHierarchyBias: 0.75,
  "vegetation.wind.motionInertia": 0.95, windMotionInertia: 0.95,
  "vegetation.wind.springResponse": 1.0, windSpringResponse: 1.0,
  "vegetation.wind.motionDamping": 1.0, windMotionDamping: 1.0,
  "vegetation.wind.parentCoupling": 0.78, windParentCoupling: 0.78,
  "vegetation.wind.gustVariance": 0.7, windGustVariance: 0.7,
  "vegetation.wind.vortexStrength": 0.55, windVortexStrength: 0.55,
  "vegetation.wind.leafMicroTurbulence": 0.6, windLeafMicroTurbulence: 0.6,
  "vegetation.wind.solverInfluence": 0.85, windSolverInfluence: 0.85,
  "vegetation.wind.branchTorsion": 0.32, windBranchTorsion: 0.32,
  "vegetation.wind.orderDrag": 0.68, windOrderDrag: 0.68,
  "vegetation.wind.gustEnvelope": 0.58, windGustEnvelope: 0.58,
  "vegetation.wind.debugSkeleton": false, windDebugSkeleton: false,

  // LOD
  "vegetation.lod.octaveCap.lod1": 5, octaveCapLod1: 5,
  "vegetation.lod.octaveCap.lod2": 3, octaveCapLod2: 3,
  "vegetation.lod.octaveCap.lod3": 2, octaveCapLod3: 2,
  "vegetation.lod.distance.nearRadius_m": 4,
  "vegetation.lod.distance.midRadius_m": 8,
  "vegetation.lod.distance.farRadius_m": 15,

  // Roots
  rootCount: 5, "vegetation.roots.rootCount": 5,
  "vegetation.roots.style": "SURFACE_SPREAD", rootStyle: "SURFACE_SPREAD",
  "vegetation.roots.visibility": 0.4, rootVisibility: 0.4,
  "vegetation.roots.shoulderLength": 0.22, rootShoulderLength: 0.22,
  "vegetation.roots.shoulderRadiusMul": 1.3, rootShoulderRadiusMul: 1.3,
};
