export type TreeParams = Record<string, number | string | boolean>;

export const DEFAULT_TREE_PARAMS: TreeParams = {
  // Instance & environment
  "vegetation.instance.age01": 1.0, age01: 1.0,
  "vegetation.env.moisture": 0.55, moisture: 0.55,
  "vegetation.env.timeOfDay": 0.45, timeOfDay: 0.45,
  "vegetation.env.autoSun": true, autoSun: true,
  "vegetation.env.autoSunInfluence": 0.82, autoSunInfluence: 0.82,
  "vegetation.env.atmosphereStrength": 0.45, atmosphereStrength: 0.45,
  "vegetation.env.contactShadowStrength": 0.62, contactShadowStrength: 0.62,
  "vegetation.env.contactShadowRadius_m": 1.65, contactShadowRadius_m: 1.65,
  "vegetation.env.shadowSoftness": 0.55, shadowSoftness: 0.55,
  "vegetation.env.nearFieldAOStrength": 0.36, nearFieldAOStrength: 0.36,
  "vegetation.env.canopySelfShadow": 0.48, canopySelfShadow: 0.48,

  // Species / trunk
  "vegetation.species.profile": "BROADLEAF_DECIDUOUS", speciesProfile: "BROADLEAF_DECIDUOUS",
  height: 8, "vegetation.species.heightBase_m": 8,
  baseRadius: 0.4, "vegetation.trunk.baseRadius_m": 0.4,
  taperExponent: 0.7, "vegetation.trunk.taperExponent": 0.7,
  baseFlare: 1.3, "vegetation.trunk.baseFlare": 1.3,
  twist: 0, "vegetation.trunk.twist_deg": 0,
  "vegetation.trunk.barkColor": "#5d4037", trunkColor: "#5d4037",
  "vegetation.trunk.barkTexture": "FURROWED", barkTexture: "FURROWED",
  "vegetation.trunk.barkRoughness": 0.75, barkRoughness: 0.75,
  "vegetation.trunk.barkAnisotropy": 0.34, barkAnisotropy: 0.34,
  "vegetation.trunk.barkMicroDetail": 0.44, barkMicroDetail: 0.44,
  "vegetation.trunk.barkCurvatureDetail": 0.4, barkCurvatureDetail: 0.4,
  "vegetation.trunk.barkFurrowDepth": 0.35, barkFurrowDepth: 0.35,
  "vegetation.trunk.barkFurrowFrequency": 6.0, barkFurrowFrequency: 6.0,
  "vegetation.trunk.barkFurrowTwist": 0.15, barkFurrowTwist: 0.15,
  "vegetation.trunk.barkPlateScale": 0.3, barkPlateScale: 0.3,
  "vegetation.trunk.barkMossBlend": 0.0, barkMossBlend: 0.0,
  "vegetation.trunk.barkMossColor": "#3a5a2a", barkMossColor: "#3a5a2a",
  "vegetation.trunk.barkLichenBlend": 0.0, barkLichenBlend: 0.0,
  "vegetation.trunk.barkLichenColor": "#8fa87a", barkLichenColor: "#8fa87a",
  "vegetation.trunk.gestureKnotCount": 2, trunkKnotCount: 2,
  "vegetation.trunk.gestureKnotStrength": 0.25, trunkKnotStrength: 0.25,
  "vegetation.trunk.gestureKnotWidth": 0.12, trunkKnotWidth: 0.12,
  "vegetation.trunk.ovality": 0.06, trunkOvality: 0.06,
  "vegetation.trunk.flutingStrength": 0, trunkFlutingStrength: 0,
  "vegetation.trunk.flutingCount": 4, trunkFlutingCount: 4,
  "vegetation.trunk.flutingSharpness": 2, trunkFlutingSharpness: 2,
  "vegetation.trunk.buttressStrength": 0, buttressStrength: 0,
  "vegetation.trunk.buttressCount": 4, buttressCount: 4,
  "vegetation.trunk.buttressSharpness": 2.2, buttressSharpness: 2.2,
  "vegetation.trunk.hollowness": 0, trunkHollowness: 0,
  "vegetation.trunk.scarCount": 0, trunkScarCount: 0,
  "vegetation.trunk.scarDepth": 0.3, trunkScarDepth: 0.3,
  "vegetation.trunk.leanAngle": 0, trunkLeanAngle: 0,
  "vegetation.trunk.crookedness": 0.1, trunkCrookedness: 0.1,

  // Bark
  "vegetation.bark.branchScale": 0.65, branchBarkScale: 0.65,
  "vegetation.bark.colorVariation": 0.08, barkColorVariation: 0.08,
  "vegetation.bark.secondaryColor": "#4a3528", barkSecondaryColor: "#4a3528",
  "vegetation.bark.secondaryBlend": 0.0, barkSecondaryBlend: 0.0,
  "vegetation.bark.wetDarkening": 0.0, barkWetDarkening: 0.0,

  // Crown shape
  "vegetation.crown.shape": "SPHERE", crownShape: "SPHERE",
  "vegetation.crown.crownRadiusRatio": 0.55, crownRadiusRatio: 0.55,
  "vegetation.crown.heightRatio": 0.75, crownHeightRatio: 0.75,
  "vegetation.crown.asymmetry": 0.1, crownAsymmetry: 0.1,
  "vegetation.crown.densityFalloff": 0.3, crownDensityFalloff: 0.3,
  "vegetation.crown.flatTop": 0, crownFlatTop: 0,
  "vegetation.crown.openness": 0.05, crownOpenness: 0.05,
  "vegetation.crown.skirt": 0.0, crownSkirt: 0.0,
  "vegetation.crown.innerVoidRadius": 0.3, crownInnerVoid: 0.3,
  "vegetation.crown.verticalBias": 0.0, crownVerticalBias: 0.0,

  // Branching
  "vegetation.branching.model": "L_SYSTEM", branchModel: "L_SYSTEM",
  "vegetation.branching.phyllotaxis": "ALTERNATE", phyllotaxis: "ALTERNATE",
  "vegetation.branching.maxOrder": 4, maxOrder: 4,
  "vegetation.branching.probability": 0.75, branchProbability: 0.75,
  "vegetation.branching.apicalDominance": 0.7, apicalDominance: 0.7,
  "vegetation.branching.angleMean_deg": 40, branchAngle: 40,
  "vegetation.branching.angleVariance_deg": 12, branchAngleVar: 12,
  "vegetation.branching.lengthDecay": 0.72, lengthDecay: 0.72,
  "vegetation.branching.radiusDecay": 0.65, radiusDecay: 0.65,
  "vegetation.branching.mainBranchCount": 8, branchCount: 8,
  "vegetation.branching.lengthRatio": 0.6, branchLength: 0.6,
  "vegetation.branching.collarStrength": 0.38, collarStrength: 0.38,
  "vegetation.branching.collarLength": 0.15, collarLength: 0.15,
  "vegetation.branching.junctionMetaballStrength": 0.55, junctionMetaballStrength: 0.55,
  "vegetation.branching.junctionMetaballRadius": 1.45, junctionMetaballRadius: 1.45,
  "vegetation.branching.unionBlendLength": 0.22, unionBlendLength: 0.22,
  "vegetation.branching.unionBlendStrength": 0.58, unionBlendStrength: 0.58,
  "vegetation.branching.unionAsymmetry": 0.42, unionAsymmetry: 0.42,
  "vegetation.branching.gestureKnotStrength": 0.25, branchKnotStrength: 0.25,
  "vegetation.branching.gestureKnotWidth": 0.18, branchKnotWidth: 0.18,
  "vegetation.branching.ovality": 0.05, branchOvality: 0.05,
  "vegetation.branching.breakProbability": 0, breakProbability: 0,
  "vegetation.branching.breakSeverity": 0.5, breakSeverity: 0.5,
  "vegetation.branching.attractorCount": 320, attractorCount: 320,
  "vegetation.branching.maxIterations": 32, maxIterations: 32,
  "vegetation.branching.skeletonIterations": 32, skeletonIterations: 32,
  "vegetation.branching.attractorPerception": 5.0, attractorPerception: 5.0,
  "vegetation.branching.attractorKill": 1.6, attractorKill: 1.6,
  "vegetation.branching.stepLength": 0, skeletonStepLength: 0,
  "vegetation.branching.pipeExponent": 0, pipeModelExponent: 0,
  "vegetation.branching.junctionBlendLength": 0.22, junctionBlendLength: 0.22,
  "vegetation.branching.junctionBlendStrength": 0.58, junctionBlendStrength: 0.58,
  "vegetation.branching.junctionAsymmetry": 0.42, junctionAsymmetry: 0.42,
  "vegetation.branching.gravityResponse": 0.12, gravityResponse: 0.12,
  "vegetation.branching.phototropism": 0.15, phototropism: 0.15,
  "vegetation.branching.phototropismDirection": 0.0, phototropismDirection: 0.0,
  "vegetation.branching.branchDroop": 0.08, branchDroop: 0.08,
  "vegetation.branching.droopIncrease": 0.04, droopIncrease: 0.04,
  "vegetation.branching.curvature": 0.15, branchCurvature: 0.15,
  "vegetation.branching.curvatureVariance": 0.1, branchCurvatureVar: 0.1,
  "vegetation.branching.forkAngle": 25, forkAngle: 25,
  "vegetation.branching.forkProbability": 0.1, forkProbability: 0.1,
  "vegetation.branching.epicormicDensity": 0, epicormicDensity: 0,
  "vegetation.branching.epicormicLength": 0.3, epicormicLength: 0.3,
  "vegetation.branching.tapering": 0.7, branchTapering: 0.7,
  "vegetation.branching.minBranchRadius": 0.005, minBranchRadius: 0.005,
  "vegetation.branching.spiralAngle": 137.5, spiralAngle: 137.5,
  "vegetation.branching.firstBranchHeight": 0.3, firstBranchHeight: 0.3,

  // Leaves
  "vegetation.leaves.representation": "CLUSTERS", leafRepresentation: "CLUSTERS",
  "vegetation.leaves.shape": "BROADLEAF", leafShape: "BROADLEAF",
  "vegetation.leaves.cardShape": "DIAMOND", leafCardShape: "DIAMOND",
  "vegetation.leaves.colorBase": "#4a7c3f", leafColor: "#4a7c3f",
  "vegetation.leaves.colorVariation": 0.15, leafColorVariation: 0.15,
  "vegetation.leaves.colorAutumn": "#c4722a", leafAutumnColor: "#c4722a",
  "vegetation.leaves.seasonalBlend": 0.0, leafSeasonalBlend: 0.0,
  "vegetation.leaves.undersideColor": "#5a8a4f", leafUndersideColor: "#5a8a4f",
  "vegetation.leaves.undersideLighten": 0.15, leafUndersideLighten: 0.15,
  "vegetation.leaves.translucency": 0.3, leafTranslucency: 0.3,
  "vegetation.leaves.specular": 0.15, leafSpecular: 0.15,
  "vegetation.leaves.size_m": 0.25, leafSize: 0.25,
  "vegetation.leaves.sizeVariation": 0.3, leafSizeVariation: 0.3,
  "vegetation.leaves.aspectRatio": 1.4, leafAspectRatio: 1.4,
  "vegetation.leaves.curl": 0.1, leafCurl: 0.1,
  "vegetation.leaves.waviness": 0.05, leafWaviness: 0.05,
  "vegetation.leaves.clusterSize": 18, leafClusterSize: 18,
  "vegetation.leaves.clusterSpread": 1.5, leafClusterSpread: 1.5,
  "vegetation.leaves.cardsPerMeter": 8, leafDensity: 8,
  "vegetation.leaves.petioleLengthFactor": 0.35, petioleLengthFactor: 0.35,
  "vegetation.leaves.petioleDroop": 0.35, petioleDroop: 0.35,
  "vegetation.leaves.petioleWidthFactor": 0.07, petioleWidthFactor: 0.07,
  "vegetation.leaves.orientationBias": 0.5, leafOrientationBias: 0.5,
  "vegetation.leaves.sunSeeking": 0.3, leafSunSeeking: 0.3,
  "vegetation.leaves.hangAngle": 15, leafHangAngle: 15,
  "vegetation.leaves.tipDroop": 0.1, leafTipDroop: 0.1,
  "vegetation.leaves.curvatureAlongMidrib": 0.15, leafMidribCurve: 0.15,
  "vegetation.leaves.edgeSerration": 0.0, leafEdgeSerration: 0.0,
  "vegetation.leaves.veinVisibility": 0.0, leafVeinVisibility: 0.0,
  "vegetation.leaves.deadLeafRatio": 0.0, deadLeafRatio: 0.0,
  "vegetation.leaves.deadLeafColor": "#8b6914", deadLeafColor: "#8b6914",
  "vegetation.leaves.fallenLeafCount": 0, fallenLeafCount: 0,

  // Flowers & fruit
  "vegetation.flowers.enabled": false, flowersEnabled: false,
  "vegetation.flowers.density": 0.1, flowerDensity: 0.1,
  "vegetation.flowers.size": 0.04, flowerSize: 0.04,
  "vegetation.flowers.color": "#e8a0bf", flowerColor: "#e8a0bf",
  "vegetation.fruit.enabled": false, fruitEnabled: false,
  "vegetation.fruit.density": 0.05, fruitDensity: 0.05,
  "vegetation.fruit.size": 0.03, fruitSize: 0.03,
  "vegetation.fruit.color": "#c44040", fruitColor: "#c44040",

  // Wind
  "vegetation.wind.gustStrength": 0.6, windStrength: 0.6,
  "vegetation.wind.enabled": true, windEnabled: true,
  "vegetation.wind.trunkBend": 0.02, trunkBend: 0.02,
  "vegetation.wind.branchBend": 0.08, branchBend: 0.08,
  "vegetation.wind.twigBend": 0.25, twigBend: 0.25,
  "vegetation.wind.canopyShear": 0.12, canopyShear: 0.12,
  "vegetation.wind.phaseRandom": 0.8, phaseRandom: 0.8,
  "vegetation.wind.restLean": 0.05, restLean: 0.05,
  "vegetation.wind.gustFrequency": 1.0, windGustFrequency: 1.0,
  "vegetation.wind.directionVariance": 0.35, windDirectionVariance: 0.35,
  "vegetation.wind.turbulence": 0.5, windTurbulence: 0.5,
  "vegetation.wind.leafFlutter": 0.35, leafFlutter: 0.35,
  "vegetation.wind.hierarchyBias": 0.75, windHierarchyBias: 0.75,
  "vegetation.wind.motionInertia": 0.95, windMotionInertia: 0.95,
  "vegetation.wind.springResponse": 1.0, windSpringResponse: 1.0,
  "vegetation.wind.motionDamping": 1.0, windMotionDamping: 1.0,
  "vegetation.wind.parentCoupling": 0.78, windParentCoupling: 0.78,
  "vegetation.wind.gustVariance": 0.7, windGustVariance: 0.7,
  "vegetation.wind.vortexStrength": 0.55, windVortexStrength: 0.55,
  "vegetation.wind.leafMicroTurbulence": 0.6, windLeafMicroTurbulence: 0.6,
  "vegetation.wind.solverInfluence": 0.85, windSolverInfluence: 0.85,
  "vegetation.wind.branchTorsion": 0.32, windBranchTorsion: 0.32,
  "vegetation.wind.orderDrag": 0.68, windOrderDrag: 0.68,
  "vegetation.wind.gustEnvelope": 0.58, windGustEnvelope: 0.58,
  "vegetation.wind.debugSkeleton": false, windDebugSkeleton: false,
  "vegetation.wind.direction_deg": 0, windDirection: 0,

  // LOD
  "vegetation.lod.octaveCap.lod1": 5, octaveCapLod1: 5,
  "vegetation.lod.octaveCap.lod2": 3, octaveCapLod2: 3,
  "vegetation.lod.octaveCap.lod3": 2, octaveCapLod3: 2,
  "vegetation.lod.distance.nearRadius_m": 4,
  "vegetation.lod.distance.midRadius_m": 8,
  "vegetation.lod.distance.farRadius_m": 15,

  // Roots
  rootCount: 5, "vegetation.roots.rootCount": 5,
  "vegetation.roots.style": "SURFACE_SPREAD", rootStyle: "SURFACE_SPREAD",
  "vegetation.roots.visibility": 0.4, rootVisibility: 0.4,
  "vegetation.roots.shoulderLength": 0.22, rootShoulderLength: 0.22,
  "vegetation.roots.shoulderRadiusMul": 1.3, rootShoulderRadiusMul: 1.3,
  "vegetation.roots.spreadRadius": 2.0, rootSpreadRadius: 2.0,
  "vegetation.roots.depth": 0.3, rootDepth: 0.3,
  "vegetation.roots.twist": 0.15, rootTwist: 0.15,
  "vegetation.roots.knobCount": 2, rootKnobCount: 2,
  "vegetation.roots.knobSize": 0.15, rootKnobSize: 0.15,
  "vegetation.roots.surfaceUndulation": 0.3, rootSurfaceUndulation: 0.3,
  "vegetation.roots.taper": 0.7, rootTaper: 0.7,
  "vegetation.roots.secondaryRoots": 0, rootSecondaryCount: 0,
  "vegetation.roots.secondaryLength": 0.4, rootSecondaryLength: 0.4,

  // Seasonal & health
  "vegetation.health.vigor": 1.0, healthVigor: 1.0,
  "vegetation.health.stress": 0.0, healthStress: 0.0,
  "vegetation.health.deadBranches": 0.0, deadBranchRatio: 0.0,
  "vegetation.health.sparseness": 0.0, canopySparseness: 0.0,
  "vegetation.seasonal.phase": 0.5, seasonalPhase: 0.5,
};
